### ISSUE TITLE
Running error, unable to load image

### ISSUE THREAD

**Issue by hmwl** [if-ai/ComfyUI_IF_AI_LoadImages#1]
I am running an error in the latest version of Comfyui. Can you provide me with more help? 
Select image prompt: Value not in list: image: 'Pink green leaves. jpg' not in []; 
Folder selection prompt: Error refreshing previews: 405: Method Not allowed

**Comment by hmwl** [comment]
To add, it refers to folders or files read on Mac

**Comment by if-ai** [comment]
oh, I am trouble here. I don't have a mac to test and fix this, hopefully someone can make a PR or I would have to wait until I can get a second hand one.

**Comment by hmwl** [comment]
Unfortunately, I also encountered the same error in Win. Or where did I operate incorrectly

**Comment by if-ai** [comment]
what browser are you useing? I am on chrome and it works, I heard reports from firfox user that it is not working on firefox

**Comment by hmwl** [comment]
yes, on chrome.

**Comment by if-ai** [comment]
Okay, I will make a tutorial on how to use the node, I think you used the upload image button I have to add a feature where it also creates a thumbnail for when you upload an individual image via the upload file. 
For now only the images upload via the select folder work, to work best you should backup your images from the input folder and then load the node start working with a empty input folder. And only upload images vuia select folder otherwise If is not this maybe you have a security feature that blocks my node for some reason

**Comment by hmwl** [comment]
Uploading QQ20241113-12223.mp4…

Yes, it may be clearer if there is a video explanation. I followed the instructions in your document, but it still doesn't work

**Comment by hmwl** [comment]
Uploading QQ20241113-12223.mp4…

**Comment by hmwl** [comment]
Yes, it may be clearer if there is a video explanation. I followed the instructions in your document, but it still doesn't work

https://github.com/user-attachments/assets/b904a702-9211-435f-ba1b-90c5680f9ca3

**Comment by if-ai** [comment]
You are doing it correctly, but I am not sure why it does not work for you  are you using a cloud provider to run comfy or a network instance? mine works perfect like I show here I think it only works on local machine https://www.youtube.com/watch?v=6ylkSoJ-Tnw

**Comment by hmwl** [comment]
My computer is local, and I tried running it on Windows, Mac, or even Linux. The problem is the same, and I don't know if anyone else has this issue. Sorry, I don't seem to be able to read your private YouTube videos

**Comment by if-ai** [comment]
Here is working but you are doing all correctly so I guess I have to discover what is going on there  https://www.youtube.com/watch?v=6ylkSoJ-Tnw can you click CTRL+shit+I after you attempt to load a folder to see if there is any useful messages please?

**Comment by hmwl** [comment]
Thank you very much. I watched the video and this node really excited me. Thank you for your reminder. I seem to have identified the issue: your other node was not installed, which caused the API to be invalid. I should need to install if_ai_tools, succeed!

**Comment by if-ai** [comment]
oh wait did't work until IF_AI tools as in then I must have an error on the init file sorry about this I will try to fix that and thanks for tell ing me about the issue

**Comment by if-ai** [comment]
OK, It was the routes because I had done a version for my node suite IF_AI_tools I endup confusing the two and send the other one here this one should work now and laso has the right order on the tensor shape
